#!/bin/sh

# Autogenerated by foreman

### BEGIN INIT INFO
# Provides:             moodies-bridge
# Required-Start:       $syslog
# Required-Stop:        $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    moodies-bridge
# Description:          moodies-bridge
### END INIT INFO

NAME=moodies-bridge
DESC=moodies-bridge
DAEMON=/home/rawouter/moodies-v1bridge/v1Bridge.py
DAEMON_USER=rawouter
PIDDIR=/var/run/moodies-bridge
PIDFILE=/var/run/moodies-bridge/moodies-bridge.pid

test -x ${DAEMON} || exit 0
set -e
. /lib/lsb/init-functions


case "${1}" in
	start)
		log_daemon_msg "Starting ${DESC}" "${NAME}"
		mkdir -p ${PIDDIR}
		if (start-stop-daemon --start --make-pidfile --background --pidfile $PIDFILE --chuid $DAEMON_USER --exec $DAEMON -- -v); then
			log_end_msg 0
		else
			log_end_msg 1
		fi
	;;
	stop)
		log_daemon_msg "Stopping ${DESC}" "${NAME}"
		if (start-stop-daemon --stop --oknodo --retry 20 --pidfile $PIDFILE --chuid $DAEMON_USER); then
			log_end_msg 0
		else
			log_end_msg 1
		fi
	;;
	status)
		status_of_proc -p ${PIDFILE} ${DAEMON} ${NAME}
	;;
	restart)
		${0} stop
		${0} start
	;;
	*)
		echo "Usage: ${0} {start|stop|status|restart}" >&2
	;;
esac

exit 0
